In [2]:
import pickle
import numpy as np
from PIL import Image

with open("peg_insert_40_demos_insert_random_long.pkl", "rb") as f:
    data = pickle.load(f)
for d in data:
    if d["rewards"] == 1:
        print(d["observations"]["state"][0][4:10])

[ 0.03754235 -0.01187267  0.09278194 -0.00544806 -0.00542228 -0.05286957]
[0.0191143  0.01797156 0.08805136 0.03360808 0.03558597 0.38939652]
[-0.01987653 -0.00198687  0.09683905 -0.00859343 -0.01081442 -0.09771588]
[-0.00820669  0.0013022   0.09566237  0.02096022  0.0266637   0.27309012]
[-0.00034514 -0.01339425  0.09836216  0.00919532  0.01498116  0.13970768]
[0.03272073 0.02734448 0.08929288 0.02923339 0.03285804 0.3514174 ]
[-0.03031181 -0.01161578  0.09379802  0.01244698  0.01749169  0.16797411]
[ 0.0347608  -0.03448138  0.09819862  0.00149823  0.00678803  0.05688445]
[ 0.03418094 -0.03191605  0.09788206  0.00086676  0.00550959  0.04440407]
[ 0.02930397  0.01336912  0.09019876 -0.0221026  -0.05261742 -0.44427273]
[-0.01894193 -0.03650918  0.10035806  0.01762109  0.02423423  0.24289331]
[-0.03057658  0.00687491  0.09362751 -0.02359327 -0.06021267 -0.5039212 ]
[-0.02244179  0.04088708  0.08849356  0.01891867  0.02358909  0.2394156 ]
[0.01014764 0.05503653 0.0906643  0.04400891 0.042

In [11]:
# 提取 wrist_1 和 wrist_2 图像数据
wrist_1_img = data[-1]['observations']['wrist_1'][0]  # 取第 0 个样本
wrist_2_img = data[-1]['observations']['wrist_2'][0]  # 取第 0 个样本

# 将 NumPy 数组转换为 Image 对象
wrist_1_img = Image.fromarray(wrist_1_img)
wrist_2_img = Image.fromarray(wrist_2_img)

# 显示图片
wrist_1_img.show(title="Wrist 1 Image")
wrist_2_img.show(title="Wrist 2 Image")