In [61]:
import pickle
import numpy as np
from PIL import Image

with open("peg_insert_40_demos_red.pkl", "rb") as f:
    data = pickle.load(f)
for d in data:
    if d["rewards"] == 1:
        print(d["observations"]["state"][0][4:10])

[-0.01009329  0.03251722  0.0889178  -0.00152522 -0.001441    0.3454264 ]
[ 0.05404496 -0.0076775   0.08847356 -0.00158404  0.00185656 -0.47528487]
[-0.02183979 -0.0174961   0.08752826 -0.00449821 -0.00298527  0.52554786]
[ 0.03093712  0.0414843   0.08888727 -0.00060655 -0.00018375  0.0404886 ]
[ 0.01137624 -0.00320062  0.08901086 -0.00228627 -0.00127075  0.25468192]
[ 0.00108717  0.00242662  0.08957824 -0.00428936 -0.00300914  0.5093916 ]
[ 0.04180993  0.01402413  0.08789612 -0.00090242 -0.00076643  0.16794379]
[-0.02801381  0.0224069   0.08944081 -0.00150777 -0.00152692  0.35968927]
[-0.01675334  0.03612633  0.08797765 -0.00155592 -0.00177482  0.42294568]
[ 0.03193109  0.00665477  0.08712552 -0.00098023  0.00032688 -0.09952001]
[-0.00845539  0.01127198  0.08899052 -0.00064124 -0.00074727  0.19965145]
[ 0.0286393   0.0526845   0.08714288 -0.00231826 -0.00130701  0.2354737 ]
[ 0.00763635  0.0352495   0.08919796 -0.00068749 -0.00045543  0.12488876]
[ 0.02548933 -0.03115617  0.08909619 -

In [49]:
# 提取 wrist_1 和 wrist_2 图像数据
wrist_1_img = data[0]['observations']['wrist_1'][0]  # 取第 0 个样本
wrist_2_img = data[0]['observations']['wrist_2'][0]  # 取第 0 个样本

# 将 NumPy 数组转换为 Image 对象
wrist_1_img = Image.fromarray(wrist_1_img)
wrist_2_img = Image.fromarray(wrist_2_img)

# 显示图片
wrist_1_img.show(title="Wrist 1 Image")
wrist_2_img.show(title="Wrist 2 Image")